### ISSUE TITLE
Data Mass

### ISSUE THREAD

**Issue by Chricky** [balexbyrd/Qlik-Sense_Extension_BoxPlot#1]
Hi, is it possible to make this extension available for data-sets larger than the standard 10k fields in the cube?

Regards
Chris

**Comment by balexbyrd** [comment]
Hey Chris,

I loaded an excel spreadsheet with 15k rows and it pulled in all of the rows. 

If you look at rows 54-75 of the Box-Plot.js file you'll see the script incrementally loading all the rows regardless of the 10k row limit. Hope this helps!
